canvas:
  api_token: demo_token_placeholder
  base_url: https://demo.instructure.com
  course_id: 12345
  course_name: 'MATH 231: Linear Algebra'
  xp_column_id: 67890
gamification:
  features:
    badges_enabled: true
    leaderboard_enabled: true
    skill_tree_enabled: true
  theme:
    name: Mathematical Adventure
    style: academic_adventure
  xp_values:
    exam: 100
    homework: 25
    participation: 10
    project: 75
    quiz: 50
privacy:
  anonymous_leaderboard: true
  data_retention_days: 365
  ferpa_compliant: true
