# Eagle Adventures 2 - Mobile Interface Configuration
# ================================================

mobile_interface:
  # Progressive Web App Settings
  pwa_enabled: true
  app_name: "Eagle Adventures 2"
  app_short_name: "EagleAdv2"
  app_description: "Gamified Mathematics Learning Platform"
  theme_color: "#1976d2"
  background_color: "#ffffff"
  display: "standalone"
  orientation: "portrait-primary"
  
  # Offline Capabilities
  offline_mode: true
  cache_strategy: "aggressive"
  offline_cache_size: 50  # MB
  sync_interval: 30  # seconds
  max_offline_actions: 100
  
  # Push Notifications
  push_notifications: true
  notification_badge_limit: 99
  vapid_configuration:
    subject: "mailto:support@eagleadventures.ewu.edu"
    public_key: "YOUR_VAPID_PUBLIC_KEY"
    private_key: "YOUR_VAPID_PRIVATE_KEY"
  
  # UI Themes and Styling
  themes:
    default: "eagle_adventures_mobile"
    dark_mode: "eagle_adventures_dark"
    accessibility: "eagle_adventures_accessible"
    colorblind_friendly: "eagle_adventures_colorblind"
  
  # Responsive Breakpoints
  breakpoints:
    mobile_small: 320   # Small phones
    mobile_medium: 375  # iPhone standard
    mobile_large: 414   # iPhone Plus/Pro
    tablet_small: 768   # iPad portrait
    tablet_large: 1024  # iPad landscape
    desktop: 1200       # Desktop screens
  
  # Touch and Gesture Settings
  gestures:
    swipe_navigation: true
    pinch_zoom: true
    long_press_menus: true
    touch_target_size: 44  # Minimum iOS standard
    gesture_sensitivity: 1.0
    haptic_feedback: true
  
  # Performance Optimization
  performance:
    lazy_loading: true
    image_compression: true
    minify_assets: true
    enable_gzip: true
    cdn_enabled: false  # Set true for production
    preload_critical_components:
      - "player_dashboard"
      - "pet_companion"
      - "navigation"
  
  # Accessibility Features
  accessibility:
    font_scaling: true
    high_contrast_mode: true
    screen_reader_support: true
    keyboard_navigation: true
    voice_control: true
    reduced_motion: true
  
  # Security Settings
  security:
    content_security_policy: true
    secure_cookies: true
    https_required: true
    token_storage: "secure"  # secure, localStorage, sessionStorage
    biometric_auth: true
  
  # Component Configuration
  components:
    player_dashboard:
      refresh_interval: 30  # seconds
      auto_save: true
      offline_capable: true
      features:
        - "pull_to_refresh"
        - "swipe_navigation"
        - "quick_actions"
    
    pet_companion:
      interaction_cooldown: 1  # seconds
      animation_quality: "high"
      sound_effects: true
      features:
        - "touch_interaction"
        - "haptic_feedback"
        - "emotional_responses"
    
    skill_tree:
      zoom_levels: [0.5, 1.0, 1.5, 2.0]
      pan_boundaries: true
      auto_center: true
      features:
        - "pinch_zoom"
        - "pan_navigation"
        - "skill_previews"
    
    quest_log:
      items_per_page: 10
      infinite_scroll: true
      offline_sync: true
      features:
        - "swipe_actions"
        - "priority_sorting"
        - "progress_visualization"
    
    guild_chat:
      message_history: 100
      real_time_updates: true
      typing_indicators: true
      features:
        - "voice_input"
        - "emoji_picker"
        - "message_reactions"
        - "file_sharing"
  
  # Notification Types and Settings
  notifications:
    quest_completed:
      enabled: true
      sound: "quest_complete.mp3"
      vibration: [200, 100, 200]
      priority: "high"
    
    level_up:
      enabled: true
      sound: "level_up.mp3"
      vibration: [500, 200, 500]
      priority: "high"
    
    pet_needs_attention:
      enabled: true
      sound: "pet_alert.mp3"
      vibration: [100, 100, 100]
      priority: "normal"
      frequency_limit: "once_per_hour"
    
    guild_message:
      enabled: true
      sound: "message.mp3"
      vibration: [100]
      priority: "normal"
    
    daily_challenge:
      enabled: true
      sound: "challenge.mp3"
      vibration: [200, 100, 200, 100, 200]
      priority: "normal"
      schedule: "09:00"  # Daily at 9 AM
    
    study_reminder:
      enabled: true
      sound: "reminder.mp3"
      vibration: [300, 100, 300]
      priority: "low"
      frequency: "daily"
  
  # Device-Specific Optimizations
  device_optimizations:
    smartphone:
      font_size_scale: 0.9
      touch_target_size: 44
      navigation_style: "bottom_tabs"
      max_concurrent_animations: 2
    
    phablet:
      font_size_scale: 1.0
      touch_target_size: 46
      navigation_style: "bottom_tabs"
      max_concurrent_animations: 3
    
    tablet:
      font_size_scale: 1.1
      touch_target_size: 48
      navigation_style: "side_drawer"
      max_concurrent_animations: 4
      enable_split_view: true
  
  # Analytics and Monitoring
  analytics:
    track_user_interactions: true
    track_performance_metrics: true
    track_offline_usage: true
    heatmap_tracking: false  # Privacy consideration
    session_recording: false  # Privacy consideration
  
  # Development and Testing
  development:
    enable_debug_mode: false
    show_performance_overlay: false
    enable_touch_visualization: false
    mock_offline_mode: false
    simulate_slow_network: false
  
  # Content Management
  content:
    image_formats: ["webp", "png", "jpg"]
    video_formats: ["mp4", "webm"]
    max_image_size: 2  # MB
    max_video_size: 10  # MB
    lazy_load_images: true
    progressive_image_loading: true
