# Privacy-Respecting Analytics Configuration
# =========================================
# FERPA-compliant analytics configuration for Eagle Adventures 2
# Prioritizes student privacy while enabling educational insights

privacy_respecting_analytics:
  # Privacy Level (essential | educational | research)
  # - essential: Minimal data, maximum privacy
  # - educational: Balanced privacy/insights for educational improvement  
  # - research: Additional data collection with explicit consent
  privacy_level: "educational"
  
  # FERPA Compliance Settings
  ferpa_compliance:
    strict_mode: true
    audit_logging: true
    automatic_compliance_checks: true
    incident_response_enabled: true
    
  # Data Anonymization
  anonymization:
    pseudonymization_enabled: true
    daily_salt_rotation: true
    k_anonymity_threshold: 5  # Minimum group size for reporting
    temporal_bucketing: "hourly"  # Prevent timing attacks
    
  # Differential Privacy
  differential_privacy:
    enabled: true
    epsilon: 1.0  # Privacy budget (lower = more private)
    delta: 0.00001
    noise_mechanism: "laplace"
    
  # Data Retention (FERPA compliance)
  data_retention:
    session_data_hours: 24
    weekly_aggregates_hours: 168    # 1 week
    monthly_aggregates_hours: 720   # 30 days
    semester_aggregates_hours: 4320 # 6 months
    research_data_hours: 8760       # 1 year (with consent)
    automatic_cleanup: true
    
  # Consent Management
  consent_management:
    research_participation_required: true
    consent_expiry_months: 12
    automatic_consent_renewal_notifications: true
    granular_consent_options: true
    
  # Data Collection Limits
  data_collection:
    # What we DON'T collect (FERPA protection)
    no_personally_identifiable_info: true
    no_individual_timestamps: true
    no_behavioral_sequences: true
    no_precise_location_data: true
    no_biometric_data: true
    
    # What we DO collect (educational purposes only)
    concept_engagement_patterns: true
    aggregated_learning_outcomes: true
    system_performance_metrics: true
    anonymized_error_patterns: true
    
  # Analytics Features
  analytics_features:
    concept_difficulty_analysis: true
    learning_path_optimization: true
    engagement_trend_analysis: true
    system_performance_monitoring: true
    educational_outcome_prediction: false  # Disabled for privacy
    individual_profiling: false           # Disabled for privacy
    behavioral_tracking: false            # Disabled for privacy
    
  # Reporting Constraints
  reporting:
    minimum_group_size: 5
    statistical_significance_threshold: 0.05
    confidence_intervals_required: true
    privacy_impact_assessments: true
    
  # Security
  security:
    encryption_at_rest: true
    encryption_in_transit: true
    secure_aggregation: true
    access_logging: true
    role_based_access_control: true
    
  # Research Data (explicit consent required)
  research_settings:
    opt_in_only: true
    informed_consent_required: true
    purpose_limitation: true
    data_minimization: true
    transparent_reporting: true
    participant_withdrawal_rights: true
    
  # Compliance Monitoring
  compliance_monitoring:
    daily_privacy_audits: true
    automated_pii_detection: true
    compliance_dashboard: true
    incident_tracking: true
    regulatory_reporting: true
